encoder_node:
  ros__parameters:
    i2c_bus: 1
    home_offset: 3072

controller_node:
  ros__parameters:
    # -- พารามิเตอร์สำหรับ Hardware Pins (เหมือนเดิม)
    step_pin: 14
    dir_pin: 15
    enable_pin: 18

    # -- พารามิเตอร์คุณลักษณะของมอเตอร์ (เหมือนเดิม)
    base_steps_per_rev: 200
    microstepping: 8
    direction_cw: 1
    direction_ccw: 0

    # -- พารามิเตอร์ใหม่! สำหรับการชดเชยมุม (องศา)
    # -- ถ้าแกนจริงชี้ไปที่ 10 องศา ทั้งที่ควรเป็น 0 ให้ใส่ค่าที่นี่เป็น -10.0
    target_offset_deg: 0.0

    # -- พารามิเตอร์ใหม่! สำหรับควบคุมความเร็ว (องศา/วินาที)
    # -- P-Control จะปรับความเร็วระหว่างค่า min กับ max นี้
    max_velocity_deg_per_sec: 100.0
    min_velocity_deg_per_sec: 10.0

    # -- พารามิเตอร์สำหรับ P-Control (เหมือนเดิม)
    tolerance_deg: 0.5
    deceleration_zone_deg: 20.0
